spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxxx?serverTimezone=UTC
    username: xxxx
    password: xxxx
    type: com.alibaba.druid.pool.DruidDataSource